--------------------------------------------------------
--  File created - Çarþamba-Ocak-20-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ORDERS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ORDERS" 
   (	"MEMBER_ID" NUMBER, 
	"BOOK_ID" NUMBER, 
	"ORDERED_DATE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.ORDERS
SET DEFINE OFF;

--------------------------------------------------------
--  DDL for Index U_O
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."U_O" ON "SYSTEM"."ORDERS" ("MEMBER_ID", "BOOK_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ORDERS" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ORDERS" ADD CONSTRAINT "U_O" UNIQUE ("MEMBER_ID", "BOOK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."ORDERS" MODIFY ("BOOK_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ORDERS" MODIFY ("ORDERED_DATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ORDERS" ADD CONSTRAINT "FK_MEMBER_ORDER" FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "SYSTEM"."MEMBERS" ("MEMBER_ID") ENABLE;
  ALTER TABLE "SYSTEM"."ORDERS" ADD CONSTRAINT "FK_BOOK_ORDER" FOREIGN KEY ("BOOK_ID")
	  REFERENCES "SYSTEM"."BOOKS" ("BOOK_ID") ENABLE;
