create or replace NONEDITIONABLE TRIGGER CategoriesAuditTrigger
BEFORE INSERT OR UPDATE OR DELETE ON Categories
FOR EACH ROW
DECLARE 
    l_date varchar(50);
BEGIN
    SELECT TO_CHAR(sysdate,'DD/MM/YYYY HH24:MI:SS') INTO l_date FROM Dual;
    IF INSERTING THEN
        INSERT INTO CATEGORY_LOG(LOG_TYPE,NEW_NAME,OLD_NAME,LOG_DATE) 
            VALUES('Kategori Ekleme',:NEW.CATEGORY_NAME, NULL, l_date);
    ELSIF UPDATING THEN
        INSERT INTO CATEGORY_LOG(LOG_TYPE,NEW_NAME,OLD_NAME,LOG_DATE) 
            VALUES('Kategori Güncelleme',:NEW.CATEGORY_NAME, :OLD.CATEGORY_NAME, l_date);
    ELSIF DELETING THEN
        INSERT INTO CATEGORY_LOG(LOG_TYPE,NEW_NAME,OLD_NAME,LOG_DATE) 
            VALUES('Kategori Silme',NULL, :OLD.CATEGORY_NAME, l_date);
    END IF;
END;